spring:
  application:
    name: audit-service
  jpa:
    hibernate:
      ddl-auto: none
      use-new-id-generator-mappings: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
  datasource:
    url: jdbc:postgresql://localhost:5432/envel
    driver-class-name: org.postgresql.Driver
    username: envel
    password: envel
    initialization-mode: always
    tomcat:
      validation-query: select 1
  flyway:
    url: jdbc:postgresql://localhost:5432/envel
    user: envel
    password: envel
    schemas: audit



logging:
  level:
    root: info
    flyway: debug
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: info
        SQL: debug
    com.envel.audit: debug
    org.keycloak: debug


graphql:
  spqr:
    gui:
      enabled: true
      page-title: Audit Service Play Ground

server:
  port: 8087
keycloak:
  auth-server-url: http://localhost:8180/auth
  realm: spring-boot
  resource: spring-boot
  credentials:
    secret: 78b8e926-e194-40c2-9285-d4ea951ae364
  bearer-only: true
  public-client: true
  #principal-attribute: preferred_username


#keycloak.security-constraints[0].authRoles[0]=user
#keycloak.security-constraints[0].securityCollections[0].patterns[0]=//*





