CREATE SEQUENCE IF NOT EXISTS account_activity_sequence START 1 INCREMENT 1;
CREATE  TABLE Account_Activity(
    ACCOUNT_ACTIVITY_ID  SERIAL PRIMARY KEY,
    ACTION VARCHAR  NOT NULL,
    ENTITY VARCHAR  NOT NULL,
    RESOURCE_ID VARCHAR  NOT NULL,
    ACTION_PROPERTY VARCHAR  NOT NULL,
    CREATED_AT TIMESTAMP  DEFAULT CURRENT_TIMESTAMP
);